### ISSUE TITLE
Unable to upload/print

### ISSUE THREAD

**Issue by yasbean** [xpierrohk/DigitalPaperApp#4]
Printing/uploading files on version 1.0 works, but on versions 1.1 and 1.2 fails with errors:
:~$ dpt print Smith.pdf
Printing Smith.pdf to Document/Received/Smith.pdf on the device
A device exception occurred: 40401 : The designated resource was not found.
net.sony.dpt.error.SonyException: The designated resource was not found.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
        at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:149)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at net.sony.util.JsonUtils.fromJSON(JsonUtils.java:19)
        at net.sony.dpt.network.CheckedHttpClient.checkString(CheckedHttpClient.java:62)
        at net.sony.dpt.network.CheckedHttpClient.getWithResponse(CheckedHttpClient.java:27)
        at net.sony.dpt.network.DigitalPaperEndpoint.resolveObjectByPath(DigitalPaperEndpoint.java:114)
        at net.sony.dpt.command.documents.DocumentCommand.delete(DocumentCommand.java:34)
        at net.sony.dpt.command.documents.DocumentCommand.upload(DocumentCommand.java:69)
        at net.sony.dpt.command.print.PrintCommand.print(PrintCommand.java:80)
        at net.sony.dpt.ui.cli.DigitalPaperCLI.print(DigitalPaperCLI.java:380)
        at net.sony.dpt.ui.cli.DigitalPaperCLI.execute(DigitalPaperCLI.java:251)
        at net.sony.dpt.DigitalPaperApp.main(DigitalPaperApp.java:35)

**Comment by xpierrohk** [comment]
Thanks for the feedback, it's super cool.
It was indeed broken and is now fixed in 1.4.0 

If you use it more than for simple curiosity, totally open to hear your feedback :)

**Comment by yasbean** [comment]
> 
> 
> Thanks for the feedback, it's super cool.
> It was indeed broken and is now fixed in 1.4.0
> 
> If you use it more than for simple curiosity, totally open to hear your feedback :)

Thank you!  Yes, I now use it as my main interface, and will continue to provide feedback.
